services:

  kirilanatur-run-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: "10001:10001"
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'KirilA2NatuR!a'
      MSSQL_PID: 'Evaluation'
    ports:
      - '1433:1433'


  kirilanatur-restore-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: "10001:10001"
    entrypoint: /bin/bash -c "
      /opt/mssql/bin/sqlservr & 
      until /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'KirilA2NatuR!a' -Q 'SELECT 1'; 
      do sleep 1; done;
      /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'KirilA2NatuR!a' -Q 'RESTORE DATABASE AdriaplinWEB FROM DISK = \"/backup/database_backup_adriaplin_prod_197.bak\" WITH MOVE \"umb_Adriaplin_upg\" TO \"/var/opt/mssql/data/AdriaplinWEB.mdf\", MOVE \"umb_Adriaplin_upg_log\" TO \"/var/opt/mssql/data/AdriaplinWEB.ldf\"'"
      
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'KirilA2NatuR!a'
      MSSQL_PID: 'Evaluation'

    ports:
      - '1433:1433'

    volumes:
      - ./kirilanatur.db:/var/opt/mssql
      - ./database_backup_adriaplin_prod_197.bak:/backup/database_backup_adriaplin_prod_197.bak
    